### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by radiaku** [thangdc/web-automation#4]
hello thangdc, 

is there any wiki, how to using this? Iam struggling how to use it :)

Second question is, How to download image in browser ( captcha ) without requesting second time?

*note
I using death by captcha API :)

![2015-04-25_233939](https://cloud.githubusercontent.com/assets/5983350/7333738/5ea54cd4-eba4-11e4-8e73-a83004d63221.png)

html code
```html
<div class="form_item " id="captcha_cont">
<div class="form_input  check rule_captcha rule_required ">
<div class="dmco_form_input dmco_form_captcha" id="captcha">
<input name="captcha" type="text" id="captchaInput" autocomplete="off" autocorrect="off" autocapitalize="off" placeholder="Salin teks" class=" check rule_captcha rule_required  text">
<div style="background-image: url(/dmcaptcha?reset=1&amp;rand=1429983437);" id="captcha_image"></div>
<div class="dmco_simplelink dmco_link">
<a href="javascript:void(0);" class="dmco_link not_ajax" title="Perbaiki" id="cantread">Perbaiki</a>
</div>
<div class="dmco_clear"></div>
</div>
</div>
</div>
```

**Comment by thangdc** [comment]
Hi radiaku,

Sorry for late feedback, Currently I don't have any wiki page, because I think the project in codeproject.com can be enough. But I will think about that.

About your problem you can try following way as bellow:

//First parameter is id of element or xpath, second parameter is location to store image
saveImageFromElement('captcha_image', 'c:\\captcha_image.png');

Please get latest code to make it work.
Thanks

**Comment by radiaku** [comment]
HI thangdc thanks for replying. 

Simple question, when I automate upload file  Ex. on youtube. ( ajax based site? )

is there any event that fired, when upload is done..? :)

**Comment by thangdc** [comment]
Hi radiaku,

No, Currently don't have any event work with ajax. But you can create an custom event.

More detail you can see here: http://stackoverflow.com/questions/21138740/how-can-i-execute-javascript-callback-function-from-c-sharp-host-application

I hope it can help.
